### ISSUE TITLE
rotate_point3d should take "from" and "to" options

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL#23]
I'm not quite sure where there need to be two rotate_point3d functions, but I think one of them should provide the from and to options that rot provides.  I'm think I'm going to need this for polyhedron manipulations.

**Comment by revarbat** [comment]
This seems like a good idea.

**Comment by revarbat** [comment]
Implemented in master branch, commit d1a9d98033c2ad2d5d2b0bc9ef76020d47c87247
