### ISSUE TITLE
sort() is slower than the version I was using

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL#29]
I didn't dig in to figure out why, but I noticed that my polyhedron code was a bit slower, having gone from 3s to 6s when I deleted the local copy of unique.  

I tested sort directly with 20k random scalars and found that it took 6s with my original code, and 28 s with the code in the library.  I assume it has to do with the complexity of the scalar test function.

**Comment by revarbat** [comment]
Rewrote compare_vals for more speed.  Master branch, commit 229b9e1e3ce7cbf39fd8723b02d6eaed63cace48
