### ISSUE TITLE
[BUG] rotate_point3d fails with errors

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL#30]
This code:

    echo(rotate_points3d([[3,3,3]], from=[-4,0,0], to=[0,0,-1]));

is giving me

    WARNING: cos() parameter could not be converted, in file lib/BOSL/math.scad, line 1288
    WARNING: sin() parameter could not be converted, in file lib/BOSL/math.scad, line 1289

and then I get [[0,0,0]] as output.

**Comment by revarbat** [comment]
Ah.  If the extra on-axis rotation isn't specified, this happens.  Fixed in master branch commit a4c4738f80f97920a34ae67186448921add56ac1
