### ISSUE TITLE
[BUG] sortidx produces incorrect result

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL#35]
data =  [[-4, 0, 0], [0, 0, -4], [0, -4, 0], [-4, 0, 0], [0, -4, 0], [0, 0, 4], [0, 0, -4], [0, 4, 0], [4, 0, 0], [0, 0, 4], [0, 4, 0], [4, 0, 0]];
echo(sorted = sort(data));
sortindex = sortidx(data);
echo(sortindex = sortindex);
echo(sorted2 = select(data,sortindex));

output is:

ECHO: sorted = [[-4, 0, 0], [-4, 0, 0], [0, -4, 0], [0, -4, 0], [0, 0, -4], [0, 0, -4], [0, 0, 4], [0, 0, 4], [0, 4, 0], [0, 4, 0], [4, 0, 0], [4, 0, 0]]
ECHO: sortindex = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
ECHO: sorted2 = [[-4, 0, 0], [0, 0, -4], [0, -4, 0], [-4, 0, 0], [0, -4, 0], [0, 0, 4], [0, 0, -4], [0, 4, 0], [4, 0, 0], [0, 0, 4], [0, 4, 0], [4, 0, 0]]

**Comment by revarbat** [comment]
Fixed in master branch commit b7e3644df324384c1ecae154bbd1004862547457
Regression tests added.
