### ISSUE TITLE
[BUG] rotate_points3d fails when from==to

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL#36]
When from and to are multiples of each other rotate_points3d is failing:

data=[[1,2,3],[4,5,6]];

echo(rotate_pionts3d(data, from=[0,0,1],to=[0,0,4]));
echo(rotate_points3d(data, from=[3,2,1],to=[6,4,2]));
echo(rotate_points3d(data,from=[0,0,1],to=[0,0,-1]));

ECHO: [[nan, nan, nan], [nan, nan, nan]]
ECHO: [[nan, nan, nan], [nan, nan, nan]]
WARNING: Ignoring unknown variable 'V_UP', in file lib/BOSL/math.scad, line 898.
WARNING: Ignoring unknown variable 'V_RIGHT', in file lib/BOSL/math.scad, line 899.
WARNING: Invalid type of parameters for cross(), in file lib/BOSL/math.scad, line 900
ECHO: [[0, 0, 0], [0, 0, 0]]

**Comment by revarbat** [comment]
Fixed in master branch commit a84dec40fc65ffac613f418f1f0a0035b992f29d
