### ISSUE TITLE
convex_hull() name confusing?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL#39]
Ok, so what's the difference between hull() and convex_hull()?  From a user perspective, I think the name "convex_hull()" doesn't at all differentiate it.  

The Linde functions return the boundary of the hull.  In 3d, the face index list, in 2d, the edge index list.  Since we already have "hull" adding the word "convex" doesn't really give any clarity.  So I wonder if 

hull_boundary,  hull3d_faces, and hull2d_edges might be good names for these functions.

**Comment by sej7278** [comment]
got to agree with you here @adrianVmariano i've no idea what this does and there's no example code or image

**Comment by revarbat** [comment]
My proposed renamings are `hull2d_path()` and `hull3d_faces()`.  Example new docs for them are already in the pre-alpha BOSL2: https://github.com/revarbat/BOSL2/wiki/hull.scad

**Comment by revarbat** [comment]
I can backport to BOSL v1 if this looks good.

**Comment by revarbat** [comment]
Not back-porting.
