### ISSUE TITLE
[BUG] cuboid doesn't apply trimcorners

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL#41]
cuboid([50, 85, 40], fillet=4, edges=EDGES_TOP, trimcorners=true);

The corners are sharp, not rounded as expected.  If I remove the "edges" specification then the corners are rounded.

**Comment by revarbat** [comment]
Rounding only occurs on corners where three rounded edges meet.  If only two, or one edge at a corner is rounded, then rounding that corner would make it not line up with the non-rounded edge or edges.
