### ISSUE TITLE
list_range(n,s,e) should return n items spaced exactly from s to e

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL#48]
The behavior of list_range when you give n, s, and e is bizzare.  It uses the step size (default 1), starts at s, and goes until either reaching e or getting to n items.  It's hard to see a use for this behavior.  

Meanwhile, the very useful case of spanning exactly from e to s with n items seems to be missing.  (Is it somewhere else?)

**Comment by revarbat** [comment]
I can see the merit in this.

**Comment by revarbat** [comment]
Implemented in 7c305fed0f5d8a8bf180b58d8c8e11f5c9eeed1c
