### ISSUE TITLE
in_list not enough?  Need something that returns index of results?

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL#5]
Do we need a function that returns all the index values where the desired entry appears in a list?  

I would rename the idx parameter to is_list to "index" to be less cryptic.

**Comment by revarbat** [comment]
You mean like the `search()` builtin?

**Comment by adrianVmariano** [comment]
Hmmm.  Yeah, search() does do this.  It wasn't apparent to me that I needed to enclose the search string in a list to make it work.
