### ISSUE TITLE
[BUG] wrong return from bezier_segment_length() in bezier.scad 

### ISSUE THREAD

**Issue by RonaldoCMP** [revarbat/BOSL#51]
The function bezier_segment_length() in bezier.scad returns what seems to be a correct result for most cases but fails in some of them. For example:

q = [[0, 0], [336, 0.016], [-15200, -0.224], [461296, -0.72]];
echo( len=bezier_segment_length(q,      0,   1/16, 0.75e-3) );
echo(len2= bezier_segment_length(q,      0,   1/16, 0.5 e-3) );
// ECHO: len = 1
// ECHO: len2 = 23.7179

For any value of max_deflect greater or equal to  0.75e-3 the returned length is 1; for smaller values of max_deflect, the returned length is  23.7179, the correct value.

That example was built in order to show that the stopping rule in bezier_segment_length() is misleading. The bezier curve in that example have a very shallow and symmetrical loop in the parameter interval [0, 1/16]. So, both conditions of the stopping rule are met in the first call and the recursion stops with a wrong result. With a tighter precision max_deflect, the rule is not met and the recursion goes on. Changing the rule to a tighter interval condition will not assert a correct result in all cases.

I approach the Bezier length computation by subdivision stopping the recursion when the Bezier control polygonal has a length near enough to the distance between the first and last point. That method, besides its correctness, is very much faster then bezier_segment_length() requiring less Bezier point evaluations.

**Comment by revarbat** [comment]
Fixed in 333088aec731a71d946ff5ab30fcebb6b067def9
