### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by donbarthel** [revarbat/BOSL#56]
The README.md says:

Axis-Positive: Towards the negative end of the axis the object is oriented on. IE: X-, Y-, or Z-.
Axis-Negative: Towards the negative end of the axis the object is oriented on. IE: X-, Y-, or Z-.

The definition of Axis-Positive should instead be:

Axis-Positive: Towards the positive end of the axis the object is oriented on. IE: X-, Y-, or Z-.

**Comment by revarbat** [comment]
README.md looked fine.  Corrected this in Home.md in wiki, though.
