### ISSUE TITLE
better name for wrap_range

### ISSUE THREAD

**Issue by adrianVmariano** [revarbat/BOSL#6]
The name wrap_range doesn't really capture the functionality.  The revised version takes various types of index sets, not just ranges.  I suggest renaming (or providing an alternate name) of select for this function.

**Comment by revarbat** [comment]
I could rename it, and deprecate the old name with a pass through.  While select() isn't a bad name, I'm an old C programmer, and select() meant something faaaaaaar different.

**Comment by adrianVmariano** [comment]
I was trying to think of alternatives to select() and the only thing that came to mind was index() which is arguably even more confusing for a C programmer, since it's meaning is something you could actually do.  There are no file descriptors in OpenSCAD.

**Comment by revarbat** [comment]
And `select()` is already used as a name in an example in the official docs. It’s probably the best choice.

**Comment by revarbat** [comment]
Deprecated `wrap_range()`.  Renamed to `select()`.  Implemented in commit [master 796fe23]
