### ISSUE TITLE
fillet_mask_x does not offer parameter center but documentation says so

### ISSUE THREAD

**Issue by fe60** [revarbat/BOSL#62]
**Describe the bug**
The documentation names "center" as a valid parameter of module fillet_mask_x [1], but the module does not accept this parameter [2].

**Code To Reproduce Bug**
```
fillet_mask_x(r=3, l=10, center=true);
```

**Expected behavior**
Add parameter "center" to modules fillet_mask_x|y|z or remove it from the documentation.

[1] https://github.com/revarbat/BOSL/wiki/masks.scad#fillet_mask_x
[2] https://github.com/revarbat/BOSL/blob/master/masks.scad#L431

**Comment by revarbat** [comment]
Removed incorrect args in docs. d80cde813614fe7812cafa5e24221cdc176d883a
