### ISSUE TITLE
[x|y|z]rot_copies() - missing hint "Overrides rots" for parameter "n".

### ISSUE THREAD

**Issue by fe60** [revarbat/BOSL#63]
**Describe the bug**
For other modules it's clearly stated in the documentation, if one parameter overrides another one (e.g. [1]). The parameter `n` of modules `[x|y|z]rot_copies()` seems to override parameter `rots` [2], but there is no hint in the documentation.

**Code To Reproduce Bug**
```
use <BOSL/transforms.scad>

zrot_copies(rots=[0,90], n=5) xmove(10) cube(size=[20, 2, 5], center=true);
```

**Expected behavior**
The documentation off all `rot_copies`-modules contains the hint "If given, overrides `rots`." for parameter `n`.

[1] https://github.com/revarbat/BOSL/wiki/transforms.scad#orient_and_align (parameter "center")
[2] https://github.com/revarbat/BOSL/blob/master/transforms.scad#L1265

**Comment by revarbat** [comment]
Fixed in ca5f5803e4b23dc428efb222a77a5865d7619038
