### ISSUE TITLE
[BUG] Unexpected cuboids at the ends of trapezoidal threaded rod

### ISSUE THREAD

**Issue by lucky62** [revarbat/BOSL#75]
**Describe the bug**
Trapezoidal rod is created with cuboids attached to the both ends of rod. 

**Code To Reproduce Bug**
```
// Code goes here.
trapezoidal_threaded_rod( l=100, d=8, pitch=2, thread_angle=15, starts=4, orient=ORIENT_Z, align=ALIGN_POS);
```

**Expected behavior**
No cuboids. Only threaded rod.

**Screenshot**
![image](https://user-images.githubusercontent.com/16965519/104041875-fda2f380-51d9-11eb-8b06-607224e44c19.png)

- OpenSCAD Version: 2019.05
- Other libraries used: None

**Comment by revarbat** [comment]
Change your view from "Thrown together" to "Preview".  Not a bug.

**Comment by lucky62** [comment]
Thanks for quick response.
