### ISSUE TITLE
[BUG] cannot find trace_polyline

### ISSUE THREAD

**Issue by jon-bondy** [revarbat/BOSL#87]
**Describe the bug**
when I go here

https://github.com/revarbat/BOSL/wiki/beziers.scad

and find the sample code for "bezier_polyline()", it includes references to "trace_polyline".  I cannot find that anywhere in the library.

In addition, the sample include and use statements at the top of the file do not work, because they say BOSL rather than BOSL2

Please either indicate where to find trace_polyline or fix the example.

**Comment by revarbat** [comment]
`trace_polyline()` is in paths.scad.  And why would BOSL1 reference code from BOSL2?  The codebases are completely separate.
